from .text_classification_datamodule import TextClassificationDataModule
from .sentence_pair_datamodule import SentencePairDataModule
from .token_classification_datamodule import TokenClassificationDataModule
from .span_classification_datamodule import SpanClassificationDataModule
from .triple_extraction_datamodule import TripleExtractionDataModule