from .text_classification import TextClassificationDataModule
from .text_pair_classification import TextPairClassificationDataModule
from .text_pair_regression import TextPairRegressionDataModule
from .token_classification import TokenClassificationDataModule
from .span_classification import SpanClassificationDataModule
from .relation_extraction import RelationExtractionDataModule
from .prompt_span_extraction import PromptSpanExtractionDataModule
from .prompt_relation_extraction import PromptRelationExtractionDataModule
